output: testing/outputs/single_json_output.json
custom_transform: customtransforms/custom_single_json_retriever.py

file_groups:
    issue_1:
        [
            "testing/resources/browsertime.json",
            "testing/resources/browsertime_copy.json",
        ]
